SELECT*
  FROM[Cinema]
  where (id%2) != 0 and[description] not like '%boring%'
  order by rating desc 

Runtime: 400 ms, faster than 64.19% of MS SQL Server online submissions for Not Boring Movies.
Memory Usage: 0B, less than 100.00% of MS SQL Server online submissions for Not Boring Movies.




USE [LEET]
GO
/****** Object:  Table [dbo].[Cinema]    Script Date: 06/27/2022 22:39:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cinema](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[movie] [nchar](1000) NULL,
	[description] [nchar](1000) NULL,
	[rating] [float] NULL,
 CONSTRAINT [PK_Cinema] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Cinema] ON 
GO
INSERT [dbo].[Cinema] ([id], [movie], [description], [rating]) VALUES (1, N'War                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ', N'great 3D                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ', 8.9)
GO
INSERT [dbo].[Cinema] ([id], [movie], [description], [rating]) VALUES (2, N'Science                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ', N'fiction                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ', 8.5)
GO
INSERT [dbo].[Cinema] ([id], [movie], [description], [rating]) VALUES (3, N'irish                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ', N'boring                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ', 6.2)
GO
INSERT [dbo].[Cinema] ([id], [movie], [description], [rating]) VALUES (4, N' Ice song                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ', N'Fantacy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ', 8.6)
GO
INSERT [dbo].[Cinema] ([id], [movie], [description], [rating]) VALUES (5, N'House card                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ', N'Interesting                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ', 9.1)
GO
SET IDENTITY_INSERT [dbo].[Cinema] OFF
GO
